import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { getProducts } from '../services'
import ProductCard from '../components/ProductCard'
import { IProduct } from '../interfaces/IProduct'
import Header from '../components/Header'
import FilterPrice from '../components/FilterPrice'
import { useProduct } from '../context/productsContext'

const Home: NextPage = () => {
  const { products, setProducts } = useProduct()
  const [productsData, setProductsData] = useState<number>(0)

  async function fetchProducts() {
    const fetchProducts = await getProducts()
    setProductsData(fetchProducts.totalItems)
    setProducts(fetchProducts.items)
  }

  useEffect( () => {
    fetchProducts()
  }, [])

  return (
    <div>
      <Head>
        <title>W/NE App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Header />
          <div className={ styles.container }>
            <FilterPrice />
            <div className={ styles.products_info}>
              <p>{ productsData } produtos encontrados</p>
              <div className={styles.products_container}>
                { !products ? '' : products.map((product) => {
                  return (
                    <ProductCard data={ product } key={ product.id }/>
                  )
                })}
              </div>
              
            </div>
          </div>
        </div>
      </main>

    </div>
  )
}

export default Home
