import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { getProducts } from '../services'
import ProductCard from '../components/ProductCard'
import { IProduct } from '../interfaces/IProduct'
import Header from '../components/Header'

const Home: NextPage = () => {
  const [products, setProducts] = useState<IProduct[]>()

  async function fetchProducts() {
    const fetch = await getProducts()
    setProducts(fetch.items)
  }

  useEffect( () => {
    fetchProducts()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>W/NE App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Header />
          <div className={styles.products_container}>
            { !products ? '' : products.map((product) => {
              return (
                <ProductCard data={ product } key={ product.id }/>
              )
            })}
          </div>
        </div>
      </main>

    </div>
  )
}

export default Home
